# server configuration
server.httpsPort: 8438
server.serviceId: com.networknt.controller-1.0.0

# controller configuration
controller.clusterMode: true

# producer format configuration
kafka-producer.bootstrap.servers: localhost:9092
kafka-producer.schema.registry.url: http://localhost:8081

# streams configuration
kafka-streams.bootstrap.servers: localhost:9092
kafka-streams.schema.registry.url: http://localhost:8081
kafka-streams.cleanUp: false
